### ISSUE TITLE
Code blocks with line numbers seems broken

### ISSUE THREAD

**Issue by dominikwilkowski** [tomfran/typo#125]
My config (yaml format)
```yml
markup:
  highlight:
    style: monokailight
    tabWidth: 2
    lineNos: true
    anchorLineNos: true
```

The markdown:
````md
```rust {hl_lines=[3,"6-9"]}
fn main() {
	let cli_flags = env::args().skip(1).collect::<Vec<String>>();
	if cli_flags.contains(&String::from("--version"))
		|| cli_flags.contains(&String::from("-v"))
		|| cli_flags.contains(&String::from("-V"))
	{
		println!("v{}", env!("CARGO_PKG_VERSION"));
		std::process::exit(0);
	}

	dotenv().ok();
	let mut game = crate::game::Game::new();
	game.play();
}
```
````

What it looks like:
<img width="836" alt="Image" src="https://github.com/user-attachments/assets/6cd63dc7-6453-4bb3-8a0d-d66aaa9b96f9" />

Note that the line numbers also get a copy button which is most likely not what we want
<img width="157" alt="Image" src="https://github.com/user-attachments/assets/28f0ba1d-49e2-4b40-ad9e-f9c12bdd4caa" />
