### ISSUE TITLE
How do I center image on post?

### ISSUE THREAD

**Issue by osBins** [tomfran/typo#3]
Hi, I loved this theme and was migrating to this theme from another.

I want to be able to control the size and alignment of the image on the posts. So far, I've been able to control the size of the images through this in my post markdown file:
```
{{< figure src="/img.jpg" width="80%">}}
```

But I haven't been able to center it. I've tried writing a custom CSS class, tried using a custom shortcode but neither worked. Can you point me in how I could do that?
And if there's a better way to control the image size as well. Thank you!

**Comment by osBins** [comment]
Update:
I've been able to center the image as well by specifying custom CSS class
```css
.center-image {
  display:flex;
  align-items: center;
  justify-content: center;
}
```

However if there is a better way to do it, I'd be happy to know.
