### ISSUE TITLE
Feature Request: Option to increase width of text

### ISSUE THREAD

**Issue by saurabh-sm** [tomfran/typo#6]
This a very good theme!

It looks like the text is occupying about 50% of screen width.

Requesting a feature for a configuration in `hugo.toml` to increase it to 75%.

**Comment by tomfran** [comment]
Hi, you can easily modify the content width as follows: 

`assets/custom.css`

```css
:root {
    --main-width: 780px;
    --main-padding: 1.4em;
}
```

I will update the wiki on custom css, but essentially everything you put there overrides existing css.

I won't add a `hugo.toml` parameter for this, as that would degenerate in possibly adding a parameter for everything css related.
